### PR TITLE
Added 'dimension text' and a text interface.

### PR DESCRIPTION
**Pull request by Pkerpo**
Utilize the new text interface to show dimensions when creating rectangles and circles.

f705fa2f-d212-4bf4-80c9-eef47f84347d
6ebf20c1-b3bd-48ee-9a8d-f2b406b83a92

### CODE REVIEW

**Comment by Pkerpo** [comment]
The text radius = 0.820 is changed to r = 0.820 in the next commit.

**Comment by Kylomask** [comment]
Simulo: Precision update

**Review by aMySour — COMMENTED** [review]
Text on a shape isn't supposed to have x, y or angle. They were intentionally left out and it's why I didn't use the text interface on SimuloShape. Text on a shape is supposed to work identically to Algodoo.

**Comment by Pkerpo** [comment]
Got it. shape text like in algodoo.

this can still be used for the dimension text right? 

`texts.push({ // height "dimension text"
                                x: (topLeftX + width) + (10 / this.viewer.cameraZoom),
                                y: topLeftY + height / 2,
                                text: height.toFixed(3),
                                color: 'white',
                                zDepth: 0,
                                fontSize: 20 / this.viewer.cameraZoom,
                                fontFamily: 'Urbanist',
                                align: 'left',
                                baseline: 'middle'
                            } as SimuloText);  `

**Pull request merged**
